language: cpp
compiler: g++
dist: trusty

addons:
  apt:
    sources:
      - ubuntu-toolchain-r-test
    packages:
      - dh-autoreconf
      - g++-5
      - libgsl0-dev

branches:
  only:
    master

script:
  - export CXX='g++-5'
  - ./autogen.sh
  - ./configure
  - make -j4
